# Generated by Django 6.0.2 on 2026-02-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_packingtask_packingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this movement', null=True),
        ),
    ]
