# Generated by Django 6.0.2 on 2026-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stockmovement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='qty_before',
            field=models.IntegerField(blank=True, help_text='Stock quantity before this movement', null=True),
        ),
    ]
